#include "../Thermal_Cabin/excel_log/Copy_Base.h"
using namespace std;
static void SetInputsValue(ExtU_Thermal_Cabin_T& Thermal_Cabin_U, float& KeCHMI_T_SetTempMLRv, float& KeCHMI_T_SetTempRRv, float& KeCHMI_T_SetTempLRv) {
	Thermal_Cabin_U. HmiCmptmtTSpForRowSecLe = 0;
	Thermal_Cabin_U. VePCAT_T_TintSp = 0;
	Thermal_Cabin_U.ActvnOfWshrFrntSafe = 0;
	Thermal_Cabin_U.AmbTRawAmbTVal1 = 0;
	Thermal_Cabin_U.AmbTRawQly = 0;
	Thermal_Cabin_U.ClimRlyCmd = 0;
	Thermal_Cabin_U.CmptmtFrntWindT = 0;
	Thermal_Cabin_U.CmptmtRelHum = 0;
	Thermal_Cabin_U.DAT_FlrLeft_Validity = 0;
	Thermal_Cabin_U.DriverAirDrictionFb = 0;
	Thermal_Cabin_U.DriverTempFlapFb = 0;
	Thermal_Cabin_U.HmiAutDefrstEna = 0;
	Thermal_Cabin_U.HmiCmptmtAirDistbnFrntLe = 0;
	Thermal_Cabin_U.HmiCmptmtAirDistbnFrntRi = 0;
	Thermal_Cabin_U.HmiCmptmtAirDistbnRe = 0;
	Thermal_Cabin_U.HmiCmptmtCoolgReq = 0;
	Thermal_Cabin_U.HmiCmptmtTSpForRowFirstLe = 0;
	Thermal_Cabin_U.HmiCmptmtTSpForRowFirstRi = 0;
	Thermal_Cabin_U.HmiCmptmtTSpSpclForRowFirstLe = 0;
	Thermal_Cabin_U.HmiCmptmtTSpSpclForRowFirstRi = 0;
	Thermal_Cabin_U.HmiCmptmtTSpSpclForRowSecLe = 0;
	Thermal_Cabin_U.HmiDefrstMaxReq = 0;
	Thermal_Cabin_U.HmiEcoClimaSetgOnOff = 0;
	Thermal_Cabin_U.HmiHvacFanLvlFrnt = 0;
	Thermal_Cabin_U.HmiHvacFanLvlRe = 0;
	Thermal_Cabin_U.HmiHvacRecircCmd = 0;
	Thermal_Cabin_U.LeSolarData1 = 0;
	Thermal_Cabin_U.PassAirDrictionFb = 0;
	Thermal_Cabin_U.PassTempFlapFb = 0;
	Thermal_Cabin_U.Power_mode_off_time = 0;
	Thermal_Cabin_U.RearAirDrictionFb = 0;
	Thermal_Cabin_U.RearTempFlapFb = 0;
	Thermal_Cabin_U.RecFlapFb = 0;
	Thermal_Cabin_U.RelHumSnsrQf = 0;
	Thermal_Cabin_U.RiSolarData1 = 0;
	Thermal_Cabin_U.VeBLWA_n_FrntBlwrSpdFb = 0;
	Thermal_Cabin_U.VeCABF_na_ACCbnClnEnaSts = 0;
	Thermal_Cabin_U.VeCADS_na_RiskLv = 0;
	Thermal_Cabin_U.VeCAQC_na_AQSEnaSts = 0;
	Thermal_Cabin_U.VeCAQC_na_AccAirdModeReq = 0;
	Thermal_Cabin_U.VeCAQC_na_AccBlwrLvReq = 0;
	Thermal_Cabin_U.VeCAQC_na_AccCbnClnEnaSts = 0;
	Thermal_Cabin_U.VeCAQC_pct_ACCRecRatReq = 0;
	Thermal_Cabin_U.VeCAQC_pct_AQSRecRatReq = 0;
	Thermal_Cabin_U.VeCCCS_na_OperSts = 0;
	Thermal_Cabin_U.VeCHMI_T_SetTempMR = 0;
	Thermal_Cabin_U.VeCHMI_na_BlwrMOff = 0;
	Thermal_Cabin_U.VeCSCC_T_SpTma = 0;
	Thermal_Cabin_U.VeCTCM_Q_AirCp = 0;
	Thermal_Cabin_U.VeCTCM_na_BpCfgActv = 0;
	Thermal_Cabin_U.VeFWDS_Pct_RecRio = 0;
	Thermal_Cabin_U.VeFWDS_T_RecTarTCtrl = 0;
	Thermal_Cabin_U.VeFWDS_na_BlwrLvReq = 0;
	Thermal_Cabin_U.VeFWDS_na_DefOpRatio = 0;
	Thermal_Cabin_U.VeFWDS_na_FANFlg = 0;
	Thermal_Cabin_U.VeFWDS_na_RECFlg = 0;
	Thermal_Cabin_U.VeGMZS_lx_SolarBckLeft = 0;
	Thermal_Cabin_U.VeGMZS_lx_SolarBckRight = 0;
	Thermal_Cabin_U.VeGMZS_lx_SolarFrtDrv = 0;
	Thermal_Cabin_U.VeGMZS_lx_SolarFrtPax = 0;
	Thermal_Cabin_U.VeGNSS_T_OutLetTemp = 0;
	Thermal_Cabin_U.VeGNSS_m_Altd = 0;
	Thermal_Cabin_U.VeHMI_na_AirdModeMR = 0;
	Thermal_Cabin_U.VeHMI_na_AirdRAutoMode = 0;
	Thermal_Cabin_U.VeHMI_na_FrntDef = 0;
	Thermal_Cabin_U.VeNVMM_U_DcRangeLoadEep = 0;
	Thermal_Cabin_U.VeNVMM_na_ActrOperCtrLoad = 0;
	Thermal_Cabin_U.VeSENA_T_AmbTemp = 0;
	Thermal_Cabin_U.VeSENA_T_ICTSts = 0;
	Thermal_Cabin_U.VeSENA_na_AmbTempQf = 0;
	Thermal_Cabin_U.VeTCFG_na_HvacVar = 0;
	Thermal_Cabin_U.VeTEEM_na_EemFrntBlowReq = 0;
	Thermal_Cabin_U.VeTemp_Fevap_Raw1 = 0;
	Thermal_Cabin_U.VeTemp_Fincar_Raw = 0;
	Thermal_Cabin_U.VeTemp_HEX_Raw = 0;
	Thermal_Cabin_U.VeTemp_feet_FL_EX_Raw1 = 0;
	Thermal_Cabin_U.VeTemp_feet_FR_EX_Raw1 = 0;
	Thermal_Cabin_U.VeTemp_feet_SL_Raw1 = 0;
	Thermal_Cabin_U.VeTemp_panel_FL_Raw1 = 0;
	Thermal_Cabin_U.VeTemp_panel_FR_Raw1 = 0;
	Thermal_Cabin_U.VeTemp_panel_SL_Raw1 = 0;
	Thermal_Cabin_U.VeVTIC_na_CrashSt = 0;
	Thermal_Cabin_U.VeVTIC_v_VehSpd = 0;
	Thermal_Cabin_U.VeXXXX_L_FrtBlwAfs = 0;
	Thermal_Cabin_U.VeXXXX_L_RrBlwAfs = 0;
	Thermal_Cabin_U.VeXXXX_Pct_FrntDrvDistbnMode = 0;
	Thermal_Cabin_U.VeXXXX_Pct_HfsOutputLt = 0;
	Thermal_Cabin_U.VeXXXX_Pct_HfsOutputRr = 0;
	Thermal_Cabin_U.VeXXXX_Pct_HfsOutputRt = 0;
	Thermal_Cabin_U.VeXXXX_Pct_RecDrPct = 0;
	Thermal_Cabin_U.VeXXXX_Pct_RrAds_Output = 0;
	Thermal_Cabin_U.VeXXXX_T_DATFlrLt = 0;
	Thermal_Cabin_U.VeXXXX_T_DATFlrRr = 0;
	Thermal_Cabin_U.VeXXXX_T_DATFlrRt = 0;
	Thermal_Cabin_U.VeXXXX_T_DATVntLft = 0;
	Thermal_Cabin_U.VeXXXX_T_DATVntRr = 0;
	Thermal_Cabin_U.VeXXXX_T_DATVntRt = 0;
	Thermal_Cabin_U.VeXXXX_T_Tevap_Tem = 0;
	Thermal_Cabin_U.VeXXXX_Wm2_Sunlnt = 0;
	Thermal_Cabin_U.VeXXXX_b_Lt_driver = 0;
	Thermal_Cabin_U.VeXXXX_b_PCATValidity = 0;
	Thermal_Cabin_U.VeXXXX_b_Rt_passenger = 0;
	Thermal_Cabin_U.VeXXXX_b_TaValidity = 0;
	Thermal_Cabin_U.VeXXXX_deg_shell_Ele = 0;
	Thermal_Cabin_U.VeXXXX_deg_shell_azi = 0;
	Thermal_Cabin_U.VeXXXX_kPa_BarPrsAbs = 0;
	Thermal_Cabin_U.VeXXXX_na_FdVStepRstSts = 0;
	Thermal_Cabin_U.VeXXXX_na_FdhStepRstSts = 0;
	Thermal_Cabin_U.VeXXXX_na_FphStepRstSts = 0;
	Thermal_Cabin_U.VeXXXX_na_FpvStepRstSts = 0;
	Thermal_Cabin_U.VeXXXX_na_RecStepRstSts = 0;
	Thermal_Cabin_U.VeXXXX_na_SdVStepRstSts = 0;
	Thermal_Cabin_U.VeXXXX_na_SdhStepRstSts = 0;
	Thermal_Cabin_U.VeXXXX_v_VehSpd = 0;
	Thermal_Cabin_U.VeXXX_na_SelfStudySts = 0;
	Thermal_Cabin_U.VeXxxx_U_SphVltgPosnFb = 0;
	Thermal_Cabin_U.VeXxxx_na_DefVltgPosnFb = 0;
	Thermal_Cabin_U.VeXxxx_na_FdhStepPosnFb = 0;
	Thermal_Cabin_U.VeXxxx_na_FdhStepRange = 0;
	Thermal_Cabin_U.VeXxxx_na_FdvStepPosnFb = 0;
	Thermal_Cabin_U.VeXxxx_na_FdvStepRange = 0;
	Thermal_Cabin_U.VeXxxx_na_FphStepPosnFb = 0;
	Thermal_Cabin_U.VeXxxx_na_FphStepRange = 0;
	Thermal_Cabin_U.VeXxxx_na_FpvStepPosnFb = 0;
	Thermal_Cabin_U.VeXxxx_na_FpvStepRange = 0;
	Thermal_Cabin_U.VeXxxx_na_RecStepPosnFb = 0;
	Thermal_Cabin_U.VeXxxx_na_RecStepRange = 0;
	Thermal_Cabin_U.VeXxxx_na_SdhStepPosnFb = 0;
	Thermal_Cabin_U.VeXxxx_na_SdhStepRange = 0;
	Thermal_Cabin_U.VeXxxx_na_SdvStepPosnFb = 0;
	Thermal_Cabin_U.VeXxxx_na_SdvStepRange = 0;
	Thermal_Cabin_U.VeXxxx_na_SphStepRange = 0;
	Thermal_Cabin_U.VehModMngtGlbSafe1UsgModSts = 0;
	Thermal_Cabin_U.VehSpdLgtA = 0;
	Thermal_Cabin_U.VehSpdLgtQf = 0;
	Thermal_Cabin_U.VehTiAndDataDataValid = 0;
	Thermal_Cabin_U.VehTiAndDataDay = 0;
	Thermal_Cabin_U.VehTiAndDataHr1 = 0;
	Thermal_Cabin_U.VehTiAndDataMins1 = 0;
	Thermal_Cabin_U.VehTiAndDataYr1 = 0;
	Thermal_Cabin_U.VeTemp_panel_FL_Raw1 = single_list[1];
	Thermal_Cabin_U.VeTemp_panel_FR_Raw1 = single_list[2];
	Thermal_Cabin_U.VeTemp_panel_SL_Raw1 = single_list[3];
	Thermal_Cabin_U.VeTemp_feet_FL_EX_Raw1 = single_list[4];
	Thermal_Cabin_U.VeTemp_feet_FR_EX_Raw1 = single_list[5];
	Thermal_Cabin_U.VeTemp_feet_SL_Raw1 = single_list[6];
	Thermal_Cabin_U.VeTemp_Fevap_Raw1 = single_list[7];
	Thermal_Cabin_U.VehSpdLgtA = single_list[8];
	Thermal_Cabin_U.VeTemp_HEX_Raw = single_list[11];
	Thermal_Cabin_U.VeTemp_Fincar_Raw = single_list[12];
	Thermal_Cabin_U.AmbTRawAmbTVal1 = single_list[13];
	Thermal_Cabin_U.CmptmtFrntWindT = single_list[20];
	Thermal_Cabin_U.VehSpdLgtQf = single_list[22];
	Thermal_Cabin_U.HmiCmptmtAirDistbnFrntLe = single_list[23];
	Thermal_Cabin_U.RelHumSnsrQf = single_list[24];
	Thermal_Cabin_U.HmiCmptmtAirDistbnFrntRi = single_list[25];
	Thermal_Cabin_U.CmptmtRelHum = single_list[26];
	Thermal_Cabin_U.HmiCmptmtAirDistbnRe = single_list[27];
	Thermal_Cabin_U.ClimRlyCmd = single_list[28];
	Thermal_Cabin_U.HmiHvacRecircCmd = single_list[29];
	Thermal_Cabin_U.HmiDefrstMaxReq = single_list[30];
	Thermal_Cabin_U.AmbTRawQly = single_list[31];
	Thermal_Cabin_U.HmiHvacFanLvlFrnt = single_list[32];
	Thermal_Cabin_U.HmiHvacFanLvlRe = single_list[33];
	Thermal_Cabin_U.VehModMngtGlbSafe1UsgModSts = single_list[34];
	Thermal_Cabin_U.HmiAutDefrstEna = single_list[35];

	KeCHMI_T_SetTempMLRv = single_list[36];
	KeCHMI_T_SetTempRRv = 24;
	KeCHMI_T_SetTempLRv = 24;
	cout << "VeTemp_panel_FR_Raw1 = " << single_list[2] <<endl;

	single_list.clear();
	uint_list.clear();
}
static void GetOutputsValue(ExtY_Thermal_Cabin_T& Thermal_Cabin_Y) {
	out_file.open(OUT_FILE, ios_base::app);
	if (!out_file.is_open()) { cout << "InitLogFile::out_file open fail!" << endl; return; }
	out_file << to_string(Thermal_Cabin_Y.VeSENA_T_FrtPassVentTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_na_CRECOperSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FrntDrvOperSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeSENA_T_FrtDrvVentTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_DefPosnCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_na_RecPosnCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeSENA_T_FrtPassFeetTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FdvPosnCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeSENA_T_FrtDrvFeetTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_na_OsaPosnCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FdfPosnCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_na_RecFlapUpdSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_DefPosnUpdSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FdvPosnUpdSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeSENA_T_FeavpTemp1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_na_OsaFlapUpdSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FdfPosnUpdSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_OperSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeSENA_T_AmbTempOut1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_na_TakeBreathTmrMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdvPosnBase) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_ReqMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeSENA_na_AmbTempFaultSt1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdfPosnBase) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_pct_OsaPosnBase) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FbMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeSENA_Wpsm_FrtDrvSolar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdvDefCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_AssignMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeSENA_Wpsm_FrtPassSolar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_pct_RecPosnBase) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdfDefCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_RangeUpdt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeSENA_Wpsm_SecDrvSolar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_pct_RecPosnNvhCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdvPosnAmbCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_StepMotorResetCmd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeSENA_T_HEXTemp1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdfPosnAmbCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_pct_OsaPosnNvhCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_ActrOperCtrSaveEep) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeSENA_T_ICT1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_DefPosnNvhCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_StepFbReady) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_pct_OsaPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdvPosnNvhCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_Stp_PreSelfStudy) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_pct_RecPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdfPosnNvhCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_V_FrntDrvVent1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_StepRstDone) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_DefPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_StepStopDone) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_pct_OsaPosnCADS) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_V_FrntDrvFoot1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_BpPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_pct_RecPosnCADS) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_V_FrntDrvDef) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdvPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdvAssignFlag) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdfPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_pct_OsaPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_V_FrntPassVent1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_DefPosnDas) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FpvAssignFlag) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_pct_RecPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_V_FrntPassFoot1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_BpPosnDas) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_pct_RecFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdvPosnDas) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_V_SecDrvVent1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdvAssignFlag) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdfPosnDas) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_pct_OsaFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_V_SecDrvFoot1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_DefPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_na_CRECFlapParkSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_T_FdTma) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_BpPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_na_TakeBreathTmrSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdfPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_T_FpTma) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdvPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdhAssignFlag) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_pct_RecPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_T_SdTma) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FrntDrvDistbnMode1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FphAssignFlag) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_na_RecStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_DefFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdhAssignFlag) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_BpFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_pct_OsaPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_pa_FlowInletRes) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdvFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_RecAssignFlag) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_na_OsaStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdfFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_pct_RecRat1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FrntDrvZoneFlapParkSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FrntPassOperSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCREC_na_RecPosnBaseQf) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FpvPosnCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FpfPosnCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdvPosnFb1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FpvPosnUpdSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdvPosnFbQf) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_na_FrntBlwrOperSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FpfPosnUpdSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Ti_Rt1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdvStsFb) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_na_FrntBlwrCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpfDefCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_na_FrntBlwrRespRate) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpvPosnAmbCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Ti_Rr) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_na_FrntBlwrUpdSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpfPosnAmbCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_v_FbFlowAmbCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpvPosnNvhCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_SurfIntAvg1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FpvPosnFb1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_v_ColdFlowLim) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpfPosnNvhCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FpvPosnFbQf) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_v_FlowCccsLim) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpvPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Ti_Lt1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FpvStsFb) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_v_FlowNvhCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpvPosnDas) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_v_FlowCalcd1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpfPosnDas) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_v_FlowEemCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpvPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_v_FlowCdds) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpfPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_v_FlowErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FrntPassDistbnMode1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_n_BlwrSpeedTar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpvFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_n_BlwrSpeedReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpfFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdvPosnFb1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_n_BlwrSpeedRamp1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FrntPassZoneFlapParkSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_TiVld) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdvPosnFbQf) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_na_FrntAirFlowLvIndc) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SecDrvOperSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdvStsFb) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_na_BlwrRlyReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SdvPosnCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[0]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[1]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[2]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[3]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[4]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[5]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[6]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[7]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[8]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[9]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[10]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[11]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[12]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[13]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[14]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[15]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[16]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Textr[17]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCAFC_v_FbFlowBase) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SdfPosnCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SdvPosnUpdSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tmtr[0]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tmtr[1]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tmtr[2]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tmtr[3]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tmtr[4]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tmtr[5]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tmtr[6]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tmtr[7]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tmtr[8]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tmtr[9]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tmtr[10]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tmtr[11]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SdfPosnUpdSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdvPosnBase) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[0]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[1]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[2]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[3]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[4]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[5]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[6]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[7]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[8]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[9]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[10]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[11]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[12]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[13]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[14]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[15]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[16]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_deg_Tintr[17]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_FrntDrvOperSt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdfPosnBase) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_FdhPosnCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdvDefCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_FdhPosnUpdSt) << ",";
	out_file << to_string(Thermal_Cabin_Y.Out167) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdfDefCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_pct_FdhPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdvPosnAmbCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[0]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[1]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[2]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[3]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[4]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[5]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[6]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[7]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[8]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[9]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[10]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[11]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[12]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[13]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[14]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[15]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[16]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_A_CabSurfAr[17]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_pct_FdhPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdfPosnAmbCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdhPosnFb1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_FdhPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdvPosnNvhCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[0]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[1]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[2]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[3]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[4]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[5]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[6]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[7]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[8]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[9]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[10]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[11]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[12]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[13]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[14]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[15]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[16]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_h_HeatCoef[17]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdhPosnFbQf) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_FdhStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdfPosnNvhCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdhStsFb) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_FdhFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdvPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FphPosnFb1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_FrntDrvZoneFlapParkSt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdvPosnDas) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FphPosnFbQf) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_FrntPassOperSt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdfPosnDas) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_OperSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FphStsFb) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_FphPosnCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdvPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdhPosnFb1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_FphPosnUpdSt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_KeepAwakeFlag) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdfPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdhPosnFbQf) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_pct_FphPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_RecCfgActv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdvFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdhStsFb) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_pct_FphPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_OsaCfgActv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdfFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_FphPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SecDrvDistbnMode1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_BCSecBlwrOperCtrl) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_FphStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SecDrvZoneFlapParkSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_FphFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_BCFrntBlwrOperCtrl) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdfPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_FrntPassZoneFlapParkSt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_DFFrntDrvOperCtrl) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpvPosnBase) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_SecDrvOperSt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_DFFrntPassOperCtrl) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpfPosnBase) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_SdhPosnCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpvDefCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_DFSecDrvOperCtrl) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_RecPosnFb1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_SdhPosnUpdSt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpfPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_RecPosnFbQf) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_pct_SdhPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_DFSecPassOperCtrl) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SecPassOperSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_RecStsFb) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_pct_SdhPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_DefCfgActv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SpvPosnCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_SdhPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_FdvCfgActv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SpfPosnCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_SdhStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SpvPosnUpdSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_FdfCfgActv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_SdhFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SpfPosnUpdSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdvStepPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_SecDrvZoneFlapParkSt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_FpvCfgActv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpfPosnBase) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdvStepType) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_SecPassOperSt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_FpfCfgActv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpvPosnBase) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdvStepBorder) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_SphPosnCalcnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_SdvCfgActv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpvDefCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_SphPosnUpdSt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpfDefCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_SdfCfgActv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_pct_SphPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpvPosnAmbCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_pct_SphPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_SpvCfgActv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpfPosnAmbCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FpvStepPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_SphPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_SpfCfgActv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpvPosnNvhCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FpvStepType) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_SphStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_AmbCmpCoeff) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpfPosnNvhCmp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FpvStepBorder) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_SphFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpvPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_FrntClimaSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHFC_na_SecPassZoneFlapParkSt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpfPosnCalcd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_SecClimaSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpvPosnDas) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_SurfIntEff0sun) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpfPosnDas) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_SurfIntEff100sun) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpvPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpfPosnErrMngt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_ECOTcsOffset) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SecPassDistbnMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdvStepPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_pct_TcsUserOffsetSclg) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpvFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdvStepType) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_Tcs0SunFd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpfFlapPosn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdvStepBorder) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_Tcs100SunFd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SecPassZoneFlapParkSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_DefPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcsStdFd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_DefStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcslvnFd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_BpPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_SurfIntEffFd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_BpStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_dTsurfFd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdvPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FdvStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcsSurfOfstFd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FdfPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_FdTcsUserOffset) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FdfStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcsFd1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_DefPosnBase) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdhStepPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_Tcs0SunFp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_BpPosnBase) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdhStepType) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpvPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_Tcs100SunFp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdhStepBorder) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FpvStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FphStepPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcsStdFp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_FpfPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FphStepType) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcslvnFp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_FpfStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FphStepBorder) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_SurfIntEffFp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdvPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdhStepPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SdvStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_dTsurfFp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdhStepType) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SdfPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdhStepBorder) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcsSurfOfstFp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SdfStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_FpTcsUserOffset) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpvPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcsFp1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SpvStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_pct_SpfPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_Tcs0SunSd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCADC_na_SpfStopReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_Tcs100SunSd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcsStdSd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_RecStepPosnReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcslvnSd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_RecStepType) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_SurfIntEffSd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_RecStepBorder) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_dTsurfSd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdvDCBorder) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcsSurfOfstSd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdfDCBorder) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_SdTcsUserOffset) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcsSd1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_Tcs0SunSp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdvDCBorder) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_Tcs100SunSp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcsStdSp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcslvnSp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdhDCBorder) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_SurfIntEffSp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FphDCBorder) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_dTsurfSp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdhDCBorder) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcsSurfOfstSp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_SpTcsUserOffset) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_RecDCBorder) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TcsSp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_P_FrntDrvHeatDem) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_P_FrntPassHeatDem) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_U_FdvMinRng) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_P_SecDrvHeatDem) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_U_FdvMaxRng) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_P_SecPassHeatDem) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_FrntDrvYn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_U_FpvMinRng) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_FrntPassYn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_U_FpvMaxRng) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_SecDrvYn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_SecPassYn) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_OperSpclStartSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_ColdStartTmrSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_U_SdvMinRng) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_HotStartTmrSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_U_SdvMaxRng) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_FdZoneModSts1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_FpZoneModSts1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_SdZoneModSts1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_SpZoneModSts1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_DefCtrlTar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_U_FdhMinRng) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_FdvCtrlTar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_U_FdhMaxRng) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_FdfCtrlTar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_U_FphMinRng) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_FpvCtrlTar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_U_FphMaxRng) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_U_SdhMinRng) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_FpfCtrlTar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_U_SdhMaxRng) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_SdvCtrlTar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_SdfCtrlTar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_SpvCtrlTar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_SpfCtrlTar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_U_RecMinRng) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_Af_FrntPassWghFlow) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_U_RecMaxRng) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_Af_SecDrvWghFlow) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_Af_SecPassWghFlow) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdvStepRange) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_Af_FrntDrvWghFlow) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FpvStepRange) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_v_FbFlowWghCtrlTar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_FdFlwTarTemp1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_FpFlwTarTemp1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdvStepRange) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_SdFlwTarTemp1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_SpFlwTarTemp1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_DtFd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdhStepRange) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_FrntDrvFlowTempOfs) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FphStepRange) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdhStepRange) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_DtFp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_FrntPassFlowTempOfs) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_DtSd) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_RecStepRange) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_SecDrvFlowTempOfs) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdvVltgPosnReq1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_DtSp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_SecPassFlowTempOfs) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FpvVltgPosnReq1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_FdTarRecTCtrl) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_FpTarRecTCtrl) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdvVltgPosnReq1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_TarRecTCrtl) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_P_FdInConEnrgChng1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_P_FpInConEnrgChng1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_P_SdInConEnrgChng1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdhVltgPosnReq1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FphVltgPosnReq1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_P_SpInConEnrgChng1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdhVltgPosnReq1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_LowestTarFlwTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_EvaNormFlwTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_EvaDefFlwTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_RecVltgPosnReq1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeNVMM_U_DcRangeSaveEep) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_EvaOutFlwTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_P_FdEvaEnrgExch1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_P_FpEvaEnrgExch1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_P_SdEvaEnrgExch1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_P_SpEvaEnrgExch1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_v_FbFlowCtrlTar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_HFFrntDrvOperCtrl) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_HFFrntPassOperCtrl) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_HFSecDrvOperCtrl) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeBLWA_pct_RatioReq1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_HFSecPassOperCtrl) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_SphCfgActv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_FdhCfgActv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_FphCfgActv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_SdhCfgActv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_ASCType) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_na_RFOperCtrl) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_RecTOffs) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_FLowestTarFlwTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_RLowestTarFlwTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_FrntEvaNormFlwTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_FrntEvaTarTemp1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_RearEvaNormFlwTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_FdHexTarFlwTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_RearEvaTarTemp1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_FpHexTarFlwTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_SdHexTarFlwTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_SpHexTarFlwTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_RearHexTarTemp1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_T_FrntHexTarTemp1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_na_RfaAutoMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_na_BlwrAutoMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_na_AirdLAutoMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_na_AirdRAutoMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_na_AirdMLAutoMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_na_AcReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_na_RfaMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_na_AirdModeL) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_na_AirdModeR) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_na_AirdModeML) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_T_SetTempL) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_T_SetTempR) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_T_SetTempML) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_na_BlwrLv) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_na_BlwrOff) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_na_DefrostReq) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_na_AutoDefSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCHMI_na_ECOSts1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeVTIC_na_WindshldWiprActivSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeSENA_T_WidShieldTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeVTIC_mps_VehSpdLgtA1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeVTIC_na_UseMode) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeVTIC_t_SoakTime) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeSENA_T_SecDrvFeetTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeSENA_T_SecDrvVentTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeSENA_pct_RelHumidity) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeVTIC_t_SoakTimeSaved) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeVTIC_t_SoakTimeLoad) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeFWDS_na_OperSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeFWDS_T_DewPntTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeFWDS_pct_RecRio) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeFWDS_pct_DefRio) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeFWDS_na_BlwrLvLim) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeFWDS_T_EvaDegTar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeFWDS_na_RiskValue1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeFDWS_na_RiskLv1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeFWDS_na_RecRioEnb) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeFWDS_na_DefRioEnb) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeFWDS_na_BlwrLvLimEnb) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeFWDS_na_EvaDegTarEnb) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_V_FrntPassFlowFb) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_V_SecDrvFlowFb) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_V_SecPassFlowFb) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_V_FrntPassDef) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_V_FrntDrvFlowFb) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCTCM_v_SecbFlowCtrlTar) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_DcFbReady) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_DcRstDone) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_DcStopDone) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdvDcType) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdfDcType) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdvDcType) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FdhDcType) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_FphDcType) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_SdhDcType) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_RecDcType) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeACTU_na_DcRangeUpdt) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_BreaTemSp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[0]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[1]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[2]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[3]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[4]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[5]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[6]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[7]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[8]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[9]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[10]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[11]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[12]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[13]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[14]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[15]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[16]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehExterSurfTempSave[17]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[0]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[1]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[2]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[3]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[4]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[5]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[6]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[7]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[8]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[9]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[10]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[11]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[12]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[13]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[14]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[15]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[16]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehIntrSurfTempSave[17]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehMidSurfTempSave[0]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehMidSurfTempSave[1]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehMidSurfTempSave[2]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehMidSurfTempSave[3]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehMidSurfTempSave[4]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehMidSurfTempSave[5]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehMidSurfTempSave[6]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehMidSurfTempSave[7]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehMidSurfTempSave[8]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehMidSurfTempSave[9]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehMidSurfTempSave[10]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehMidSurfTempSave[11]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehBreaTempSave[0]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehBreaTempSave[1]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehBreaTempSave[2]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_T_VehBreaTempSave[3]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_PCATOperSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[0]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[1]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[2]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[3]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[4]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[5]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[6]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[7]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[8]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[9]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[10]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[11]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[12]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[13]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[14]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[15]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[16]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellMass18[17]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[0]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[1]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[2]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[3]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[4]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[5]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[6]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[7]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[8]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[9]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[10]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[11]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[12]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[13]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[14]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[15]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[16]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellCp18[17]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[0]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[1]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[2]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[3]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[4]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[5]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[6]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[7]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[8]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[9]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[10]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[11]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[12]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[13]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[14]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[15]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[16]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellHtCndvty18[17]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[0]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[1]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[2]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[3]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[4]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[5]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[6]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[7]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[8]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[9]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[10]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[11]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[12]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[13]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[14]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[15]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[16]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_ShellThick18[17]) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_na_NapTimrSts) << ",";
	out_file << to_string(Thermal_Cabin_Y.VePCAT_t_NapTimr) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_m_FrEvaNormFlwOutHum) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_m_ReEvaNormFlwOutHum) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_m_RecFlwInHum) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_T_DuctAvgTemp) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeCSCC_pwr_SloarAvgPwr) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeTemp_panel_FR_Raw) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeTemp_panel_FL_Raw) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeTemp_feet_FR_EX_Raw) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeTemp_feet_FL_EX_Raw) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeTemp_feet_SL_Raw) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeTemp_panel_SL_Raw) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeTemp_Fevap_Raw) << ",";
	out_file << to_string(Thermal_Cabin_Y.AmbTRawAmbTVal) << ",";
	out_file << to_string(Thermal_Cabin_Y.VehSpdLgtA1) << ",";
	out_file << to_string(Thermal_Cabin_Y.LeSolarData) << ",";
	out_file << to_string(Thermal_Cabin_Y.RiSolarData) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeTemp_HEX_Raw1) << ",";
	out_file << to_string(Thermal_Cabin_Y.VeTemp_Fincar_Raw1) << ",";
	out_file << to_string(Thermal_Cabin_Y.DriverTempFlapFb1) << ",";
	out_file << to_string(Thermal_Cabin_Y.PassTempFlapFb1) << ",";
	out_file << to_string(Thermal_Cabin_Y.RearTempFlapFb1) << ",";
	out_file << to_string(Thermal_Cabin_Y.DriverAirDrictionFb1) << ",";
	out_file << to_string(Thermal_Cabin_Y.PassAirDrictionFb1) << ",";
	out_file << to_string(Thermal_Cabin_Y.RearAirDrictionFb1) << ",";
	out_file << to_string(Thermal_Cabin_Y.RecFlapFb1) << ",";
	out_file << "\n";
	out_file.close();
}
